.TH  q1-2_tracker 3 "December 13, 2016" "Version 1.0" "Manuel de q1-2_tracker"
.SH NAME
.B q1-2_tracker \- Pseudo-tracker P2P.
.SH SYNOPSIS
.B ./q1-2_tracker traddr trport
.SH DESCRIPTION
Pseudo-tracker P2P. Peut lister des gens qui se connectent a lui pour annoncer
un hash ou pour le recuperer.
.SH RETURN VALUE
CA RENVOIE RIEN MDR
.SH OPTIONS
Options :
.TP
\fBtraddr\fP
Adresse IPv6 sur laquelle on ecoute.
.TP
\fBtrport\fP
Port sur lequel
.SH LICENCE
Ce logiciel est soumis a la GNU General Public License.
.SH AUTHOR
\fBNicolas Sutter & Theo Poizat\fP
