.TH  q1-3_tracker 3 "December 13, 2016" "Version 1.0" "Manuel de q1-3_tracker"
.SH NAME
.B q1-3_tracker \- Pseudo-tracker P2P avec expiration des relations hash-client.
.SH SYNOPSIS
.B ./q1-3_tracker traddr trport
.SH DESCRIPTION
Pseudo-tracker P2P avec expiration des relations hash-client. Peut lister des gens qui se connectent a lui pour annoncer
un hash ou pour le recuperer. Supprime les relations hash-client non utilises depuis un certain temps enregistres dans le code source.
.SH OPTIONS
Options :
.TP
\fBtraddr\fP
Adresse IPv6 sur laquelle on ecoute.
.TP
\fBtrport\fP
Port sur lequel
.SH LICENCE
Ce logiciel est soumis a la GNU General Public License.
.SH AUTHOR
\fBNicolas Sutter & Theo Poizat\fP
