.TH  q1-3_client 3 "December 13, 2016" "Version 1.0" "Manuel de q1-3_client"
.SH NAME
.B q1-3_client \- Pseudo-client P2P avec expiration des relations hash-client.
.SH SYNOPSIS
.B ./q1-3_client traddr trport clport type hash
.SH DESCRIPTION
Pseudo-client P2P avec expiration des relations hash-client. Peut annoncer un hash (fictif) et recuperer la liste des IPs qui fournissent ce hash.
Envoi a intervalle regulier des messages KEEP_ALIVE (duree definie dans le code source) pour conserver
l'association has-client.
.SH OPTIONS
Options :
.TP
\fBtraddr\fP
Adresse IPv6 du tracker.
.TP
\fBtrport\fP
Port du tracker.
.TP
\fBclport\fP
Port de notre programme sur lequel on va ecouter les reponses du tracker.
.TP
\fBtype\fP
Type du message
.br
put = on annonce un hash
.br
get = on demande un hash
.TP
\fBhash\fP
Hash annonce/demande.
.SH LICENCE
Ce logiciel est soumis a la GNU General Public License.
.SH AUTHOR
\fBNicolas Sutter & Theo Poizat\fP
