.TH  q1-4_seeder 3 "December 13, 2016" "Version 1.0" "Manuel de q1-4_seeder"
.SH NAME
.B q1-4_seeder \- Seeder P2P d'un fichier.
.SH SYNOPSIS
.B ./q1-4_seeder port fichier
.SH DESCRIPTION
Ecoute sur le port passe en parametre, et pour un hash donne (celui de fichier), envoie la liste des chunks de ce fichier.
Permet egalement d'envoyer ce fichier en multiple segments.
.SH OPTIONS
Options :
.TP
\fBport\fP
Port sur lequel on ecoute.
.TP
\fBfichier\fP
Fichier qu'on propose en seed.
.SH LICENCE
Ce logiciel est soumis a la GNU General Public License.
.SH AUTHOR
\fBNicolas Sutter & Theo Poizat\fP
