.TH  q1-4_leecher 3 "December 13, 2016" "Version 1.0" "Manuel de q1-4_leecher"
.SH NAME
.B q1-4_leecher \- Leecher P2P d'un fichier.
.SH SYNOPSIS
.B ./q1-4_leecher seedadresse seedport port hash output
.SH DESCRIPTION
Demande au seeder specifie en parametre le fichier caracterise par le hash en parametre et, en cas de succes, le telecharge et le stocke dans output.
.SH OPTIONS
Options :
.TP
\fBseedadresse\fP
Adresse du seeder auquel on se connecte.
.TP
\fBseedport\fP
Port du seeder auquel on se connecte.
.TP
\fBport\fP
Port sur lequel on ecoute les reponses du seeder.
.TP
\fBhash\fP
Hash du fichier qu'on demande au seeder.
.TP
\fBoutput\fP
Fichier de sortie recu par le seeder.
.SH LICENCE
Ce logiciel est soumis a la GNU General Public License.
.SH AUTHOR
\fBNicolas Sutter & Theo Poizat\fP
